name: Stylua check

on: push

jobs:
  stylua:
    name: Stylua
    runs-on: puzl-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
